version: "3"
services:
       reunion:
           container_name: reunion
           image: reunion
           restart: always
           build: .
           ports:
             - "80:11395"
           links:
             - mongo
       mongo:
             container_name: mongo
             image: mongo
             volumes:
               - ./data:/data/db
             ports:
               - '27018:27017'